site_name: Fan Qing Song's Site
site_description: Personal website with resume and knowledge base
site_author: Fan Qing Song
site_url: https://fanqingsong.github.io

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.highlight
    - search.share
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode

nav:
  - Home: index.md
  - About Me: about-me.md
  - Knowledge Base:
    - Overview: knowledge-base/index.md
    - Cheat Sheet: knowledge-base/cheat_sheet.md
    - Linux Commands: knowledge-base/linux_command.md
    - Git Commands: knowledge-base/git_command.md
    - Node.js: knowledge-base/nodejs.md
    - Docker:
      - Container: knowledge-base/docker_container.md
      - Image: knowledge-base/docker_image.md
      - Misc: knowledge-base/docker_misc.md
    - MySQL:
      - Setup on WSL: knowledge-base/mysql_install_on_WSL.md
      - Commands: knowledge-base/mysql_commands.md
    - Python: knowledge-base/python_commands.md
    - SQLAlchemy:
      - SQLAlchemy: knowledge-base/sqlalchemy_sqlalchemy.md
      - Alembic: knowledge-base/sqlalchemy_alembic.md
  - DevOps:
    - PostgreSQL:
      - Sync: devops/sync-postgres.md
      - Backup: devops/postgres-backup.md
      - Restore: devops/postgres-restore.md
    - Neo4j:
      - Sync: devops/sync-neo4j.md
      - Backup: devops/neo4j-backup.md
      - Restore: devops/neo4j-restore.md

plugins:
  - search

markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.smartsymbols
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
